# Inserting Libraries

In [25]:
import numpy as np
import pandas as pd
from datetime import datetime

In [26]:
df = pd.read_csv("weather_dataset_stage1.xls - Sheet 1 - weather_dataset (2).csv")

In [27]:
df.head(30)

,weather_dataset,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,tableName,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date\tVARCHAR(512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,temperature\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Average humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Average dewpoint (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Average barometer (in\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Average windspeed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Average gustspeed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Average direction (°deg\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Rainfall for month (in\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Rainfall for year (in\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Maximum rain per minute\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Maximum temperature (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Minimum temperature (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Maximum humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Minimum humidity (%\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Maximum pressure\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Minimum pressure\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Maximum windspeed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Maximum gust speed (mph\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Maximum heat index (°F\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Date1\tVARCHAR(512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Month\tINT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,diff_pressure\tDOUBLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
28,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
29,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'

# Dropping Null Values

In [28]:
df.dropna(inplace=True)
df.head()

,weather_dataset,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
27,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
28,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
29,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
30,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
31,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'

# Renaming All Collumns

In [29]:
df.rename( columns={'weather_dataset':'Date',
                    'Unnamed: 1':'Temperature','Unnamed: 2':'Average_humidity',
                    'Unnamed: 3':'Average_dewpoint','Unnamed: 4':'Average_barometer',
                    'Unnamed: 5':'Average_windspeed','Unnamed: 6':'Average_gustspeed',
                    'Unnamed: 7':'Average_direction','Unnamed: 8':'Rainfall_for_month',
                    'Unnamed: 9':'Rainfall_for_year','Unnamed: 10':'Maximum_rain_per_minute',
                    'Unnamed: 11':'Maximum_temperature','Unnamed: 12':'Minimum_temperature',
                    'Unnamed: 13':'Maximum_humidity','Unnamed: 14':'Minimum_humidity',
                    'Unnamed: 15':'Maximum_pressure','Unnamed: 16':'Minimum_pressure',
                    'Unnamed: 17':'Maximum_windspeed','Unnamed: 18':'Maximum_gust_speed',
                    'Unnamed: 19':'Maximum_heat_index','Unnamed: 20':'Date1',
                    'Unnamed: 21':'Month','Unnamed: 22':'diff_pressure'}, inplace=True )

In [30]:
df.head()

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Date1,Month,diff_pressure
27,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
28,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
29,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
30,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
31,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'

In [31]:
df.drop(index=27,axis=0)

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Date1,Month,diff_pressure
28,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
29,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
30,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
31,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'
32,2022-01-05','23.5','30.0','-5.3','29.9','16.7','23.1','265.0','0.0','0.0',...,'5.0','13.0','30.233','29.568','38.0','53.0','32.0','2022-01-05','01','0.6649999999999991'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3926,2022-07-25','62.8','60.0','48.1','29.7','2.5','4.0','242.0','0.33','4.47',...,'90.0','36.0','29.781','29.645','8.1','17.3','77.5','2022-07-25','07','0.13599999999999923'
3927,2022-07-26','60.6','68.0','48.9','29.8','1.7','2.9','357.0','0.33','4.47',...,'90.0','40.0','29.93','29.745','11.5','15.0','77.5','2022-07-26','07','0.18499999999999872'
3928,2022-07-27','61.7','64.0','47.4','29.9','2.2','4.0','66.0','0.33','4.47',...,'96.0','35.0','29.941','29.781','13.8','18.4','78.2','2022-07-27','07','0.16000000000000014'
3929,2022-07-28','60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49',...,'94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';
3930,2022-07-28','60.5','61.0','45.3','29.7','4.0','6.2','248.0','0.35','4.49',...,'94.0','35.0','29.792','29.675','17.3','26.5','77.6','2022-07-28','07','0.11700000000000088';

# Resetting Index To 0

In [32]:
df.reset_index(drop=True,inplace=True)
df.head()

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Date1,Month,diff_pressure
0,Date,Temperature,Average humidity (%,Average dewpoint (°F,Average barometer (in,Average windspeed (mph,Average gustspeed (mph,Average direction (°deg,Rainfall for month (in,Rainfall for year (in,...,Maximum humidity (%,Minimum humidity (%,Maximum pressure,Minimum pressure,Maximum windspeed (mph,Maximum gust speed (mph,Maximum heat index (°F,Date1,Month,diff_pressure
1,2022-01-01,'37.8','35.0','12.7','29.7','26.4','36.8','274.0','0.0','0.0',...,'4.0','27.0','29.762','29.596','41.4','59.0','40.0','2022-01-01','01','0.16600000000000037'
2,2022-01-02','43.2','32.0','14.7','29.5','12.8','18.0','240.0','0.0','0.0',...,'4.0','16.0','29.669','29.268','35.7','51.0','52.0','2022-01-02','01','0.4009999999999998'
3,2022-01-03','25.7','60.0','12.7','29.7','8.3','12.2','290.0','0.0','0.0',...,'8.0','35.0','30.232','29.26','25.3','38.0','41.0','2022-01-03','01','0.9719999999999978'
4,2022-01-04','9.3','67.0','0.1','30.4','2.9','4.5','47.0','0.0','0.0',...,'7.0','35.0','30.566','30.227','12.7','20.0','32.0','2022-01-04','01','0.33899999999999864'

# Removing Apostrophe from all the data points

In [33]:
df.drop(0,inplace=True)

In [34]:
df['Date'] = df['Date'].str.replace(r"'","")
df['Temperature'] = df['Temperature'].str.replace(r"'","")
df['Average_humidity'] = df['Average_humidity'].str.replace(r"'","")
df['Average_dewpoint'] = df['Average_dewpoint'].str.replace(r"'","")
df['Average_barometer'] = df['Average_barometer'].str.replace(r"'","")
df['Average_windspeed'] = df['Average_windspeed'].str.replace(r"'","")
df['Average_gustspeed'] = df['Average_gustspeed'].str.replace(r"'","")
df['Average_direction'] = df['Average_direction'].str.replace(r"'","")
df['Rainfall_for_month'] = df['Rainfall_for_month'].str.replace(r"'","")
df['Rainfall_for_year'] = df['Rainfall_for_year'].str.replace(r"'","")
df['Maximum_rain_per_minute'] = df['Maximum_rain_per_minute'].str.replace(r"'","")
df['Maximum_temperature'] = df['Maximum_temperature'].str.replace(r"'","")
df['Minimum_temperature'] = df['Minimum_temperature'].str.replace(r"'","")
df['Maximum_humidity'] = df['Maximum_humidity'].str.replace(r"'","")
df['Minimum_humidity'] = df['Minimum_humidity'].str.replace(r"'","")
df['Maximum_pressure'] = df['Maximum_pressure'].str.replace(r"'","")
df['Minimum_pressure'] = df['Minimum_pressure'].str.replace(r"'","")
df['Maximum_windspeed'] = df['Maximum_windspeed'].str.replace(r"'","")
df['Maximum_gust_speed'] = df['Maximum_gust_speed'].str.replace(r"'","")
df['Maximum_heat_index'] = df['Maximum_heat_index'].str.replace(r"'","")
df['Date1'] = df['Date1'].str.replace(r"'","")
df['Month'] = df['Month'].str.replace(r"'","")
df['diff_pressure'] = df['diff_pressure'].str.replace(r"'","")
df.head()

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Date1,Month,diff_pressure
1,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,...,4.0,27.0,29.762,29.596,41.4,59.0,40.0,2022-01-01,01,0.16600000000000037
2,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,...,4.0,16.0,29.669,29.268,35.7,51.0,52.0,2022-01-02,01,0.4009999999999998
3,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,...,8.0,35.0,30.232,29.26,25.3,38.0,41.0,2022-01-03,01,0.9719999999999978
4,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,...,7.0,35.0,30.566,30.227,12.7,20.0,32.0,2022-01-04,01,0.33899999999999864
5,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,...,5.0,13.0,30.233,29.568,38.0,53.0,32.0,2022-01-05,01,0.6649999999999991

In [35]:
df.columns

Index(['Date', 'Temperature', 'Average_humidity', 'Average_dewpoint',
       'Average_barometer', 'Average_windspeed', 'Average_gustspeed',
       'Average_direction', 'Rainfall_for_month', 'Rainfall_for_year',
       'Maximum_rain_per_minute', 'Maximum_temperature', 'Minimum_temperature',
       'Maximum_humidity', 'Minimum_humidity', 'Maximum_pressure',
       'Minimum_pressure', 'Maximum_windspeed', 'Maximum_gust_speed',
       'Maximum_heat_index', 'Date1', 'Month', 'diff_pressure'],
      dtype='object')

# Changing Data Type Of All Columns

In [36]:
df['Temperature'] = df['Temperature'].astype(float)
df['Average_humidity'] = df['Average_humidity'].astype(float)
df['Average_dewpoint'] = df['Average_dewpoint'].astype(float)
df['Average_barometer'] = df['Average_barometer'].astype(float)
df['Average_windspeed'] = df['Average_windspeed'].astype(float)
df['Average_gustspeed'] = df['Average_gustspeed'].astype(float)
df['Average_direction'] = df['Average_direction'].astype(float)
df['Rainfall_for_month'] = df['Rainfall_for_month'].astype(float)
df['Rainfall_for_year'] = df['Rainfall_for_year'].astype(float)
df['Maximum_rain_per_minute'] = df['Maximum_rain_per_minute'].astype(float)
df['Maximum_temperature'] = df['Maximum_temperature'].astype(float)
df['Minimum_temperature'] = df['Minimum_temperature'].astype(float)
df['Maximum_humidity'] = df['Maximum_humidity'].astype(float)
df['Minimum_humidity'] = df['Minimum_humidity'].astype(float)
df['Maximum_pressure'] = df['Maximum_pressure'].astype(float)
df['Minimum_pressure'] = df['Minimum_pressure'].astype(float)
df['Maximum_windspeed'] = df['Maximum_windspeed'].astype(float)
df['Maximum_gust_speed'] = df['Maximum_gust_speed'].astype(float)
df['Maximum_heat_index'] = df['Maximum_heat_index'].astype(float)
df['Month'] = df['Month'].astype(int)

In [37]:
df.drop(columns=['Date1'],axis=1,inplace=True)

# Removing ';' from data points

In [38]:
df['diff_pressure'] = df['diff_pressure'].str.replace(r";","")
df['diff_pressure'] = df['diff_pressure'].astype(float)

In [39]:
df.head()

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Month,diff_pressure
1,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.0,0.0,...,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,1,0.166
2,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.0,0.0,...,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,1,0.401
3,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.0,0.0,...,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,1,0.972
4,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.0,0.0,...,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,1,0.339
5,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.0,0.0,...,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,1,0.665

# Dropping Duplicates

In [40]:
df.drop_duplicates()

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Month,diff_pressure
1,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,...,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,1,0.166
2,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,...,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,1,0.401
3,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,...,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,1,0.972
4,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,...,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,1,0.339
5,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,...,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,1,0.665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3898,2022-07-24,64.1,62.0,49.8,29.6,3.6,5.8,240.0,0.24,4.38,...,55.3,86.0,35.0,29.686,29.577,15.0,25.3,77.4,7,0.109
3899,2022-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,...,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,7,0.136
3900,2022-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,...,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5,7,0.185
3901,2022-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,...,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,7,0.160
3902,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,7,0.117

# Removing Invalid Date

In [41]:
indexAge = df[df['Date']=='2022-02-29'].index
df.drop(indexAge , inplace=True)
df.head(30)

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Month,diff_pressure
1,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,...,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,1,0.166
2,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,...,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,1,0.401
3,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,...,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,1,0.972
4,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,...,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,1,0.339
5,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,...,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,1,0.665
6,2022-01-06,24.8,42.0,4.6,29.8,16.0,23.9,276.0,0.00,0.00,...,19.0,5.0,27.0,29.879,29.637,29.9,48.0,32.0,1,0.242
7,2022-01-07,34.2,60.0,21.6,29.7,20.4,30.0,276.0,0.00,0.00,...,27.0,8.0,46.0,29.860,29.602,38.0,54.0,39.0,1,0.258
8,2022-01-08,42.1,41.0,20.0,29.8,17.5,25.2,265.0,0.00,0.00,...,36.0,5.0,28.0,29.883,29.627,35.7,49.0,51.0,1,0.256
9,2022-01-09,30.3,46.0,11.4,30.0,6.9,10.6,292.0,0.00,0.00,...,19.0,8.0,27.0,30.446,29.575,24.2,36.0,41.0,1,0.871
10,2022-01-10,26.2,38.0,3.6,30.4,18.2,24.6,258.0,0.00,0.00,...,22.0,4.0,29.0,30.489,30.291,31.1,46.0,32.0,1,0.198
11,2022-01-11,30.1,41.0,9.0,30.3,17.0,24.6,270.0,0.00,0.00,...,26.0,5.0,29.0,30.421,30.112,31.1,44.0,36.0,1,0.309
12,2022-01-12,23.4,60.0,11.0,30.3,7.4,11.0,351.0,0.03,0.03,...,16.0,8.0,41.0,30.524,30.012,25.3,33.0,32.0,1,0.512
13,2022-01-13,32.4,47.0,14.6,30.2,16.3,22.6,254.0,0.03,0.03,...,28.0,5.0,34.0,30.340,30.046,32.2,47.0,38.0,1,0.294
14,2022-01-14,33.1,45.0,14.2,30.2,9.9,14.0,259.0,0.03,0.03,...,28.0,5.0,34.0,30.271,30.115,29.9,32.0,39.0,1,0.156
15,2022-01-15,35.7,42.0,14.5,30.3,7.9,11.8,270.0,0.03,0.03,...,27.0,5.0,28.0,30.405,30.201,19.6,26.0,43.0,1,0.204
16,2022-01-16,41.6,28.0,9.7,30.3,11.9,16.7,269.0,0.03,0.03,...,32.0,4.0,14.0,30.432,30.127,26.5,37.0,53.0,1,0.305
17,2022-01-17,40.9,21.0,3.1,30.3,6.7,9.7,276.0,0.03,0.03,...,28.0,2.0,11.0,30.435,30.093,21.9,26.0,54.0,1,0.342
18,2022-01-18,43.4,15.0,-1.7,30.3,9.6,14.7,288.0,0.03,0.03,...,27.0,2.0,8.0,30.425,30.190,24.2,36.0,52.0,1,0.235
19,2022-01-19,46.6,19.0,3.6,30.3,7.0,10.5,293.0,0.03,0.03,...,36.0,3.0,7.0,30.333,30.154,20.7,28.0,57.0,1,0.179
20,2022-01-20,40.0,27.0,-1.0,30.4,4.8,7.4,285.0,0.03,0.03,...,16.0,6.0,4.0,30.607,30.016,18.4,26.0,61.0,1,0.591
21,2022-01-21,48.2,11.0,-4.6,30.0,12.4,16.8,257.0,0.03,0.03,...,41.0,1.0,6.0,30.143,29.871,25.3,35.0,55.0,1,0.272
22,2022-01-22,44.8,40.0,20.8,29.9,11.8,16.3,264.0,0.03,0.03,...,38.0,6.0,17.0,29.911,29.784,31.1,44.0,52.0,1,0.127
23,2022-01-23,24.8,81.0,19.6,30.2,3.7,5.3,52.0,0.03,0.03,...,12.0,8.0,63.0,30.473,29.855,12.7,16.0,38.0,1,0.618
24,2022-01-24,35.4,68.0,25.0,30.0,8.2,10.8,281.0,0.09,0.09,...,13.0,9.0,40.0,30.436,29.689,26.5,35.0,47.0,1,0.747
25,2022-01-25,21.0,77.0,14.5,29.9,4.3,6.1,35.0,0.20,0.20,...,5.0,9.0,45.0,30.138,29.652,23.0,26.0,39.0,1,0.486
26,2022-01-26,2.8,73.0,-4.0,30.3,3.9,5.6,51.0,0.20,0.20,...,-3.0,7.0,65.0,30.535,29.879,15.0,20.0,32.0,1,0.656
27,2022-01-27,7.9,51.0,-8.1,30.4,12.7,17.7,263.0,0.20,0.20,...,-11.0,7.0,25.0,30.619,30.131,34.5,47.0,32.0,1,0.488
28,2022-01-28,21.8,43.0,2.6,30.2,19.6,28.0,269.0,0.20,0.20,...,15.0,5.0,31.0,30.250,30.063,43.7,58.0,32.0,1,0.187
29,2022-01-29,22.5,40.0,1.3,30.3,9.4,14.4,267.0,0.20,0.20,...,15.0,5.0,27.0,30.408,30.240,28.8,47.0,32.0,1,0.168
30,2022-01-30,36.0,33.0,9.4,30.3,15.7,21.3,261.0,0.21,0.21,...,27.0,4.0,22.0,30.435,30.102,32.2,44.0,46.0,1,0.333

In [42]:
df['Date'] = pd.to_datetime(df['Date'])

In [43]:
df

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Minimum_temperature,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Month,diff_pressure
1,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,...,34.0,4.0,27.0,29.762,29.596,41.4,59.0,40.0,1,0.166
2,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,...,37.0,4.0,16.0,29.669,29.268,35.7,51.0,52.0,1,0.401
3,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,...,6.0,8.0,35.0,30.232,29.260,25.3,38.0,41.0,1,0.972
4,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,...,-0.0,7.0,35.0,30.566,30.227,12.7,20.0,32.0,1,0.339
5,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,...,15.0,5.0,13.0,30.233,29.568,38.0,53.0,32.0,1,0.665
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3899,2022-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,...,55.1,90.0,36.0,29.781,29.645,8.1,17.3,77.5,7,0.136
3900,2022-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,...,50.5,90.0,40.0,29.930,29.745,11.5,15.0,77.5,7,0.185
3901,2022-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,...,43.6,96.0,35.0,29.941,29.781,13.8,18.4,78.2,7,0.160
3902,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,7,0.117
3903,2022-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,46.0,94.0,35.0,29.792,29.675,17.3,26.5,77.6,7,0.117

# Making Year Corrections

In [44]:
from datetime import datetime, timedelta
df['year_offset'] = (df['Date'] == datetime(2022, 1, 1)).cumsum() - 1
df['Date'] = df.apply(lambda x: x['Date'].replace(year=x['Date'].year + x['year_offset']), axis=1)

In [45]:
df

,Date,Temperature,Average_humidity,Average_dewpoint,Average_barometer,Average_windspeed,Average_gustspeed,Average_direction,Rainfall_for_month,Rainfall_for_year,...,Maximum_humidity,Minimum_humidity,Maximum_pressure,Minimum_pressure,Maximum_windspeed,Maximum_gust_speed,Maximum_heat_index,Month,diff_pressure,year_offset
1,2022-01-01,37.8,35.0,12.7,29.7,26.4,36.8,274.0,0.00,0.00,...,4.0,27.0,29.762,29.596,41.4,59.0,40.0,1,0.166,0
2,2022-01-02,43.2,32.0,14.7,29.5,12.8,18.0,240.0,0.00,0.00,...,4.0,16.0,29.669,29.268,35.7,51.0,52.0,1,0.401,0
3,2022-01-03,25.7,60.0,12.7,29.7,8.3,12.2,290.0,0.00,0.00,...,8.0,35.0,30.232,29.260,25.3,38.0,41.0,1,0.972,0
4,2022-01-04,9.3,67.0,0.1,30.4,2.9,4.5,47.0,0.00,0.00,...,7.0,35.0,30.566,30.227,12.7,20.0,32.0,1,0.339,0
5,2022-01-05,23.5,30.0,-5.3,29.9,16.7,23.1,265.0,0.00,0.00,...,5.0,13.0,30.233,29.568,38.0,53.0,32.0,1,0.665,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3899,2033-07-25,62.8,60.0,48.1,29.7,2.5,4.0,242.0,0.33,4.47,...,90.0,36.0,29.781,29.645,8.1,17.3,77.5,7,0.136,11
3900,2033-07-26,60.6,68.0,48.9,29.8,1.7,2.9,357.0,0.33,4.47,...,90.0,40.0,29.930,29.745,11.5,15.0,77.5,7,0.185,11
3901,2033-07-27,61.7,64.0,47.4,29.9,2.2,4.0,66.0,0.33,4.47,...,96.0,35.0,29.941,29.781,13.8,18.4,78.2,7,0.160,11
3902,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,94.0,35.0,29.792,29.675,17.3,26.5,77.6,7,0.117,11
3903,2033-07-28,60.5,61.0,45.3,29.7,4.0,6.2,248.0,0.35,4.49,...,94.0,35.0,29.792,29.675,17.3,26.5,77.6,7,0.117,11

# Dropping Duplicate Column

In [46]:
df.drop('year_offset', axis=1, inplace =True)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3901 entries, 1 to 3903
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     3901 non-null   datetime64[ns]
 1   Temperature              3901 non-null   float64
 2   Average_humidity         3901 non-null   float64
 3   Average_dewpoint         3901 non-null   float64
 4   Average_barometer        3901 non-null   float64
 5   Average_windspeed        3901 non-null   float64
 6   Average_gustspeed        3901 non-null   float64
 7   Average_direction        3901 non-null   float64
 8   Rainfall_for_month       3901 non-null   float64
 9   Rainfall_for_year        3901 non-null   float64
 10  Maximum_rain_per_minute  3901 non-null   float64
 11  Maximum_temperature      3901 non-null   float64
 12  Minimum_temperature      3901 non-null   float64
 13  Maximum_humidity         3901 non-null   float64
 14  Minimum_humidity         3901 non-null   float64
 15  Maximum_pressure         3901 non-null   float64
 16  Minimum_pressure         3901 non-null   float64
 17  Maximum_windspeed        3901 non-null   float64
 18  Maximum_gust_speed       3901 non-null   float64
 19  Maximum_heat_index       3901 non-null   float64
 20  Month                    3901 non-null   int32
 21  diff_pressure            3901 non-null   float64
dtypes: datetime64[ns](1), float64(20), int32(1)
memory usage: 685.7 KB

# Exporting Cleaned File as CSV

In [48]:
df.to_csv(r'C:\Users\Taniya\Downloads\clean_dataset.csv', index=False)